name: Build CMake preset
description: Build CMake preset

inputs:
  preset:
    description: CMake preset to build
    required: true

  cmakeExtraArgs:
    description: Extra arguments to pass to CMake
    required: false

  artifactBindir:
    description: Path to the binary output directory (relative to build directory)
    required: false
    default: bin

  artifactSuffix:
    description: Suffix appended to the artifact name
    required: false

  artifactExtraPaths:
    description: Extra paths to be added to build artifact
    required: false

outputs:
  build-artifact-name:
    description: Name of the uploaded build artifact
    value: ${{ steps.set-output.outputs.build-artifact-name }}

runs:
  using: composite
  steps:
    - name: Build CMake preset
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. --preset ${{ inputs.preset }} ${{ inputs.cmakeExtraArgs }}
        make -j$(nproc)

    - name: Set artifact name
      id: set-output
      shell: bash
      run: echo "build-artifact-name=build-${{ inputs.preset }}${{ inputs.artifactSuffix }}" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v6
      with:
        name: ${{ steps.set-output.outputs.build-artifact-name }}
        path: |
          build/${{ inputs.artifactBindir }}
          ${{ inputs.artifactExtraPaths }}
